version: '3.7'
services:
  app:
    tty: yes
    container_name: app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    build: ./docker/php
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:8000
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

